/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiPerpus;

import akun.user;
import buku.DaoBuku;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import peminjamanBuku.DAOpeminjaman;

/**
 *
 * @author revan
 */
public class panelInfo extends javax.swing.JPanel {
    Connection con;
    user pengguna;
    /**
     * Creates new form panelInfo
     */
    public panelInfo() {
        initComponents();
    }
    
      public panelInfo(Connection con, user pengguna) {
        
        
        initComponents();
        
        this.con = con;
        this.pengguna = pengguna;
        
        this.jTextArea1.setVisible(false);
        this.tabelInfoBuku();
        this.tabelInfoBukuDipinjam();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInfoBukuDipinjam = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInfoBukuBaru = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        tableInfoBukuDipinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Buku", "Tanggal Pinjam", "Jatuh Tempo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableInfoBukuDipinjam);

        jLabel2.setText("Buku Baru!");

        jLabel3.setText("Peminjaman");

        tableInfoBukuBaru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Judul Buku", "Kategori", "Posisi", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableInfoBukuBaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableInfoBukuBaruMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableInfoBukuBaru);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INFO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel4.setText("Deskripsi Buku: ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void tabelInfoBukuDipinjam(){
        DAOpeminjaman daopinjam = new DAOpeminjaman();
        ResultSet rs = daopinjam.lihatPeminjaman(con, this.pengguna);
        
        
        DefaultTableModel model = (DefaultTableModel) this.tableInfoBukuDipinjam.getModel();
        model.setRowCount(0);
        try{
          while(rs.next()){
            
            Object[]row = {rs.getString("id_buku"),rs.getString("tanggal_pinjam"), daopinjam.hitungJatuhTempo(rs.getString("tanggal_pinjam"))};  
            model.addRow(row);
          }
            
        } catch (SQLException ex) {
            Logger.getLogger(panelInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void tabelInfoBuku(){
       
        
        DaoBuku daobuku = new DaoBuku();
        ResultSet rs = daobuku.infoBukuBaru(con);
            
        DefaultTableModel model = (DefaultTableModel) tableInfoBukuBaru.getModel();
        
        try{
          while(rs.next()){
            Object[]row = {rs.getString("judul"),rs.getString("kategori"),rs.getString("posisi"),rs.getString("status")};  
            model.addRow(row);
          }
            
        } catch (SQLException ex) {
            Logger.getLogger(panelInfo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    
    private void tableInfoBukuBaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableInfoBukuBaruMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable)evt.getSource();
        int baris = source.rowAtPoint( evt.getPoint() );
        int kolom = 0;
        String getKlik=source.getModel().getValueAt(baris, kolom).toString();
        
        DaoBuku daobuku = new DaoBuku();
        ResultSet rs = daobuku.cariBuku(this.con, getKlik, "Judul");
        
        try {
            if(rs.next()){
                this.jTextArea1.setVisible(true);

                this.jTextArea1.setText(rs.getString("deskripsi"));
            }else{
                this.jTextArea1.setVisible(true);

                this.jTextArea1.setText("tidak terdapat deskripsi");
            }
        } catch (SQLException ex) {
            Logger.getLogger(panelInfo.class.getName()).log(Level.SEVERE, null, ex);
        }

        System.out.println(getKlik);
    }//GEN-LAST:event_tableInfoBukuBaruMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tableInfoBukuBaru;
    private javax.swing.JTable tableInfoBukuDipinjam;
    // End of variables declaration//GEN-END:variables
}
